### ISSUE TITLE
Foreign should be Feature not Object

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#10]
`foreign` is currently turned into an object where it should actually be a feature of the `morpheme` object.

**Comment by hvlaardingerbroek** [comment]
The reason is that sometimes only part of what we call morpheme is marked `foreign`, with a non-foreign suffix attached. Another option would be to put the marked part of the morpheme in the feature, but that seemed more complicated (maybe it isn't).

**Comment by codykingham** [comment]
I wonder 2 things: 1) should we then consider something marked as a foreign set of chars as an individual morpheme itself? and 2) if not, we can mark them as features of `char`s. There is also no reason we can't mark the `foreign` feature on both morphemes and chars where appropriate.

**Comment by hvlaardingerbroek** [comment]
1. I would not chop up morphemes on 'foreign' boundaries, since it would be inconsistent (the same suffix on an Aramaic word would not be recognized as 'morpheme').
2. That is probably the best. You keep the detail by marking the `char`s, but you simplify things by marking the morpheme containing any foreign chars as foreign.

It is not a very common phenomenon, and we also can't be sure that it is used consistently. Very possibly other foreign words with Aramaic endings are entirely marked foreign, or not at all - both defensible in a way. So it is not something we should rely on (unless we can prove that we can), but I did not want to lose the information.

**Comment by codykingham** [comment]
Agreed.

**Comment by codykingham** [comment]
Done. I've changed the name from "foreign" to `language` and it is now a feature of chars rather than an object.
Update: see commit https://github.com/CambridgeSemiticsLab/nena_corpus/commit/69182029151c98ae2c0fad6bd53c8bdf69d718f3
