### ISSUE TITLE
Word Endings

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#3]
In the present TF implementation, word emphases are modeled as individual characters (slots). For example, notice the gap between the first two words, from slot 5 to slot 8. 
```
ʾìθwa
	1 ʾ
	2 ì
	3 θ
	4 w
	5 a
xa-ràbbən
	8 x
	9 a
	10 -
	11 r
	12 à
	13 b
	14 b
	15 ə
	16 n
```
This is because the following characters are modeled as slots:

```
6 |
7  
```
That is, slot 6 is a word-ending stress and slot 7 is a space. This way of modeling could make searching for adjacent words more difficult. I propose we settle for a mediating position: characters should indeed be slots. But word stresses and spacing should be stored as a `char` feature, `ending.tf`. For example, on char 5 there would be a feature `F.ending.v(5)` with a value of `"| "`. 

This would mean we alter the `otext` metadata to the following:

```
otext = {
    'sectionTypes': 'text,paragraph,line,sentence',
    'sectionFeatures': 'text_id,line',
    'fmt:text-orig-full': '{char}{ending}'
}
```

So TF will format a char and its ending. Every char will thus have an ending feature. If the ending is null, it will be a simple empty string. This is similar to BHSA's [trailer feature](https://etcbc.github.io/bhsa/features/trailer_utf8/), except it is stored at the character level.

Doing it this way allows us to keep the strengths of character encoding (e.g. ability to model sub-word units like morphemes), without weakening the importance of word adjacency.

**Comment by hvlaardingerbroek** [comment]
I have no problem with this proposal, although to be honest I do not see the immediate necessity (but that is probably due to my lack of experience with TextFabric).

The words `ʾìθwa` and `xa-ràbbən` do have their own slots (let's say numbered 12321 and 12322), so as words, they are adjacent, right? There is nothing in between, so if you are looking for a word followed by another word, or even a morpheme followed by another morpheme, they should be considered adjacent. But if you are looking for a word followed by a certain character like a full stop or a comma, or an em dash, you can also find it, because the characters adjacent to the word characters are a full stop or a comma or an em dash.

If you do not want that (there are probably reasons I am not aware of), does it then make sense to encode them as `trailer` or `ending` of the last character? Or of the word, or of the morpheme? Or (I think the most logical option) all three?

I think the `trailer` solution makes more sense in the BHSA, where the smallest node is the word, and there is no sensible way to encode something that is not a word, coming between words, but where you do want to record things that come between words. But since we chose the character as smallest unit, I think it is somewhat artificial to not use it also for characters coming between words.

But all that said, those are not fundamental objections, and I can be easily convinced with examples of TF queries that would be hard or impossible. If it makes querying the corpus with TF easier then I shall implement it.

**Comment by codykingham** [comment]
The problem is that TF does not yet have an object-adjacency function, but calculates adjacency purely in terms of slots.

So the following query, which looks for two adjacent words, will not work the way we have implemented it now:

```
word 
<: word
```

It is possible to specify that an intervening space slot could occur, but this is cumbersome and not sensitive to cases where a space and a punctuation slot occur.

At the root of the issue is this: we can choose to meticulously model every mark as an individual slot. But we should only do so if the information is necessary and useful. We will not annotate features on top of space slots, and probably not on top of punctuation slots. So I see no practical benefit for modeling them as objects.

In fact, the only usefulness of punctuation/spacing is for printing the text. The `trailer` solution treats the markings as features rather than objects. There can be a single feature `txt` for characters and words. A `char` `txt` feature contains the character text + `trailer`. The `word` `txt` feature contains the sum total of all character `txt` features. The word `txt` feature is necessary to facilitate querying, for example:

```
word txt=yuma
```

**Comment by hvlaardingerbroek** [comment]
Ok I see what you mean. It still feels a bit artificial to me to make interpunction a feature of the last character of a word -- I would say then it makes more sense to make it a feature of the whole word -- but for the implementation that probably makes no difference.

**Comment by codykingham** [comment]
The main motivation for making it a feature of `char` is admittedly to accommodate the `T.text` function, which formats the plain text representation of objects in TF (see [here](https://annotation.github.io/text-fabric/Api/Text/)). `T.text` uses the metadata in otext:

```
otext = {
    'fmt:text-orig-full': '{char}{trailer}'
}
```

If we changed it to `{word}{trailer}`, then the `T.text` function call would not work on `char` or `morpheme` objects.

It IS possible to define optional formats, such as:

```
otext = {
     'fmt:char-orig-full:'{char}',
     'fmt:text-orig-full:'{word}{trailer}'
}
``` 
But this means that when you call `T.text(char)` you have to say additionally `fmt='char-orig-full'`.

**Comment by codykingham** [comment]
There is actually some confusion here, on my part. I am not sure whether `otext` is capable of using objects above slot-level...So where it says `{word}{trailer}`, I am causing some confusion, because "word" implies that is an object. But it seems that `otext` takes **features**, which would mean the slot level may be mandatory...Asking Dirk about that. 

btw, [here is](https://annotation.github.io/text-fabric/Create/CreateTF/) docs for otext feature

**Comment by codykingham** [comment]
Ok! So we CAN do `char` and `word` formatting differently, which is great actually...

See the documentation [here](https://annotation.github.io/text-fabric/Api/Text/#text-representation)

Also see the [`otext` file](https://github.com/ETCBC/dss/blob/master/tf/0.6/otext.tf) for the DSS corpus. 

In this case, I agree wholeheartedly. `trailer` should be a feature of words only. We need only format the `otext` accordingly. Waiting for details from Dirk.

**Comment by hvlaardingerbroek** [comment]
I have stored the `trailer` on the `char` object, as in your original proposal (see https://github.com/CambridgeSemiticsLab/nena_corpus/commit/2c233a657857a1e079b7485715ae4bbba0e25e07).

I have looked at the documentation you and Dirk mentioned, which was very instructive and enlightening, but I still couldn't figure out all the way how to get the feature on the `word` object (which goes to show that your proposal was indeed the most straightforward way to do it).

I would still like to get `trailer` on `word`, so for that I made a new issue #6, in which I copied your comments, and this one I consider closed.
