### ISSUE TITLE
Replace | (0x7c) with ᶥ (0x1da5)

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#5]
The prosody marker `|` is originally superscript in the source texts. According to Geoffrey, these should be kept as superscripts if possible. I propose we replace | with  ᶥ (e.g. instead of `ʾìθwa|` it would be `ʾìθwaᶥ`). 

The new char would be hex `0x1da5 `

**Comment by hvlaardingerbroek** [comment]
I have deliberately chosen to keep it a simple vertical bar, just as for the double hyphen I have chosen the 'equals' symbol. The reason is that it is easier to type, and it is shown the same in any font, and it is a unique character (meaning that it is not used for any other purpose). When we want to present the text, we can always replace it (with the choice to use markup such as `<sup>|</sup>` 'ʾìθwa<sup>|</sup>' or the unicode character `0x1da5` 'ʾìθwaᶥ').

Another option, related to issues #3 and #4, is to leave out the vertical bar altogether and only encode the delimited segment as a prosaic unit, the same way the language markers and verse/line numbers are not encoded as slots in the text. In that case it can be reconstructed for presentation purposes, again either with markup or with the unicode character.

I think the latter is the best option, but I am open for any solution.

**Comment by hvlaardingerbroek** [comment]
By implementing prosaic unit objects as proposed in issue #4 (https://github.com/CambridgeSemiticsLab/nena_corpus/commit/9ffd36ad42c8335b9f4f2938e0ce7b8da23a2c6e), the vertical bar is no longer encoded in the TF database, so the exact character to represent it is now at the discretion of the rendering program.

**Comment by codykingham** [comment]
I don't agree actually. When printing large portions of the corpus, the prosaic units should be preserved as they are in the source materials. This is a bit like the accent marks in the Hebrew text. Yes, as you say, the prosaic units are still recoverable in the database. But when I'm printing sentence objects, for instance, I should be able to see in the printed text where the prosaic unit ends.

**Comment by codykingham** [comment]
> The reason is that it is easier to type, and it is shown the same in any font, and it is a unique character (meaning that it is not used for any other purpose).

The UTF8 text already contains characters that are complicated to type. Proposal: Model UTF8 text as "pretty" as possible—it should be nice to look at, and contain as much UTF8 magik as possible. This would be contained in the `txt` feature. Then we implement a transcription feature (`trans`) to facilitate ease of search. The `|` symbol can be implemented as you say. But also other letters will be transcribed differently, so as to make them easily type-able. E.g. `ḥ` could become something like `x` in the transcription.

**Comment by hvlaardingerbroek** [comment]
I did not say it was a *good* reason 😉

I agree with your proposal. Then, also the plus symbol can be in superscript. And maybe also the foreign language markers, as they were in the text?

The main problem then becomes, considering issue #3, where to store the characters -- that would have to be the `trailer` feature then, right? But with the language markers also there, those might become a bit crowded?

**Comment by hvlaardingerbroek** [comment]
But are you sure that `0x1da5` is the correct symbol? In some fonts it looks like a superscript vertical bar, but in others it looks like a greek iota (which it is) - and in others, like the github code font on my android phone, it doesn't render at all (shows a box). Do you know a better alternative? (I did not find one yet)

**Comment by hvlaardingerbroek** [comment]
There is `0x02c8` `ˈ` `modifier letter vertical line` but it is so small you can hardly see it

**Comment by codykingham** [comment]
I actually like that 0x02c8 char. So just combining it with line 1 from Barwar A49 gives:

> qarə́kke ṱ-íla kùmtaˈ xá-yoma ʾay-tìwtaˈ

It is also the closest thing to the superscript pipe that Geoffrey uses.

**Comment by codykingham** [comment]
It is unobtrusive at least.

**Comment by hvlaardingerbroek** [comment]
Vertical line is now replaced with Unicode 0x02c8: https://github.com/CambridgeSemiticsLab/nena_corpus/commit/a32979ae66847f608db01e78caa78074faf55e06
